"""
DevSynt Task 6 - AI Email Triage & RAG Assistant

Decision Engine

Takes the classification result from classifier.py and determines
what should happen to the incoming email.

Important:
- AI does not make hiring decisions.
- AI does not make business decisions.
- Important emails are routed to humans.
- Unknown/low-confidence cases are escalated.
- Promotional and spam emails are not forwarded to employees.
"""

from typing import Dict, Any


# ---------------------------------------------------------
# Action constants
# ---------------------------------------------------------

ACTION_RAG = "rag_answer"
ACTION_HR = "forward_and_notify_hr"
ACTION_MANAGER = "forward_and_notify_manager"
ACTION_MEETING = "notify_responsible_person"
ACTION_URGENT = "immediate_human_notification"
ACTION_ARCHIVE = "archive_or_delete"
ACTION_SPAM = "move_to_spam"
ACTION_HUMAN = "human_review"


# ---------------------------------------------------------
# Decision Engine
# ---------------------------------------------------------

def decide_action(
    classification: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Convert an email classification into a safe operational action.

    Parameters:
        classification:
            Output generated by classifier.py.

    Returns:
        Dictionary describing the action that the automation
        should perform.
    """

    category = classification.get("category", "other")
    priority = classification.get("priority", "medium")
    confidence = float(classification.get("confidence", 0.0))
    requires_human = bool(
        classification.get("requires_human", True)
    )

    # -----------------------------------------------------
    # Safety rule:
    # Low confidence always goes to human review.
    # -----------------------------------------------------

    if confidence < 0.75:
        return {
            "action": ACTION_HUMAN,
            "destination": "human_review",
            "requires_human": True,
            "priority": priority,
            "reason": (
                "Classification confidence is below the "
                "safe automation threshold."
            ),
        }

    # -----------------------------------------------------
    # Urgent / Critical
    # -----------------------------------------------------

    if category == "urgent_request" or priority == "critical":
        return {
            "action": ACTION_URGENT,
            "destination": "urgent_management",
            "requires_human": True,
            "priority": "critical",
            "discord_channel": "urgent-management",
            "reason": (
                "Urgent or critical email requires immediate "
                "human attention."
            ),
        }

    # -----------------------------------------------------
    # Job Application → HR
    # -----------------------------------------------------

    if category == "job_application":
        return {
            "action": ACTION_HR,
            "destination": "hr",
            "requires_human": True,
            "priority": "high",
            "discord_channel": "hr",
            "reason": (
                "Job application must be forwarded to HR. "
                "The AI does not make hiring decisions."
            ),
        }

    # -----------------------------------------------------
    # Project / Internal → Manager
    # -----------------------------------------------------

    if category in {
        "project_related",
        "internal_communication",
        "complaint",
    }:
        return {
            "action": ACTION_MANAGER,
            "destination": "manager",
            "requires_human": True,
            "priority": priority,
            "discord_channel": "manager",
            "reason": (
                "This email concerns a project, internal matter, "
                "or complaint and requires human management."
            ),
        }

    # -----------------------------------------------------
    # Meeting Request → Human
    # -----------------------------------------------------

    if category == "meeting_request":
        return {
            "action": ACTION_MEETING,
            "destination": "responsible_person",
            "requires_human": True,
            "priority": priority,
            "discord_channel": "manager",
            "reason": (
                "Meeting requests require human confirmation. "
                "The system must not automatically schedule meetings."
            ),
        }

    # -----------------------------------------------------
    # Promotional → Archive/Delete
    # -----------------------------------------------------

    if category == "promotional":
        return {
            "action": ACTION_ARCHIVE,
            "destination": "archive",
            "requires_human": False,
            "priority": "low",
            "reason": (
                "Promotional email can be archived or deleted "
                "without forwarding to employees."
            ),
        }

    # -----------------------------------------------------
    # Spam → Spam folder
    # -----------------------------------------------------

    if category == "spam":
        return {
            "action": ACTION_SPAM,
            "destination": "spam",
            "requires_human": False,
            "priority": "low",
            "reason": (
                "Strong spam indicators were detected."
            ),
        }

    # -----------------------------------------------------
    # General Query → RAG
    # -----------------------------------------------------

    if category == "general_query":
        return {
            "action": ACTION_RAG,
            "destination": "rag",
            "requires_human": requires_human,
            "priority": priority,
            "reason": (
                "General question should be answered using "
                "the Task 5 knowledge base."
            ),
        }

    # -----------------------------------------------------
    # Sales Inquiry → RAG or Human
    # -----------------------------------------------------

    if category == "sales_inquiry":
        return {
            "action": ACTION_RAG,
            "destination": "rag",
            "requires_human": requires_human,
            "priority": priority,
            "reason": (
                "Sales inquiry should use the knowledge base. "
                "If the required information is unavailable, "
                "the email must be escalated to a human."
            ),
        }

    # -----------------------------------------------------
    # Unknown / Other → Human Review
    # -----------------------------------------------------

    return {
        "action": ACTION_HUMAN,
        "destination": "human_review",
        "requires_human": True,
        "priority": priority,
        "reason": (
            "The email does not match a safe automated route."
        ),
    }


# ---------------------------------------------------------
# Convenience function
# ---------------------------------------------------------

def process_classification(
    classification: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Wrapper function used by the main email-processing pipeline.
    """

    decision = decide_action(classification)

    return {
        "classification": classification,
        "decision": decision,
    }


# ---------------------------------------------------------
# Local testing
# ---------------------------------------------------------

if __name__ == "__main__":

    test_cases = [
        {
            "category": "job_application",
            "priority": "high",
            "requires_human": True,
            "confidence": 0.96,
        },
        {
            "category": "sales_inquiry",
            "priority": "medium",
            "requires_human": False,
            "confidence": 0.89,
        },
        {
            "category": "project_related",
            "priority": "high",
            "requires_human": True,
            "confidence": 0.91,
        },
        {
            "category": "meeting_request",
            "priority": "medium",
            "requires_human": True,
            "confidence": 0.93,
        },
        {
            "category": "urgent_request",
            "priority": "critical",
            "requires_human": True,
            "confidence": 0.97,
        },
        {
            "category": "promotional",
            "priority": "low",
            "requires_human": False,
            "confidence": 0.88,
        },
        {
            "category": "spam",
            "priority": "low",
            "requires_human": False,
            "confidence": 0.94,
        },
        {
            "category": "other",
            "priority": "medium",
            "requires_human": True,
            "confidence": 0.52,
        },
    ]

    print("\nDevSynt Task 6 - Decision Engine Test")
    print("=" * 60)

    for number, classification in enumerate(
        test_cases,
        start=1
    ):

        result = decide_action(classification)

        print(f"\nTest Case {number}")
        print("-" * 60)
        print(f"Category: {classification['category']}")
        print(f"Priority: {classification['priority']}")
        print(f"Confidence: {classification['confidence']}")
        print(f"Action: {result['action']}")
        print(f"Destination: {result['destination']}")
        print(f"Human Required: {result['requires_human']}")
        print(f"Reason: {result['reason']}")
